# Generated by Django 4.1.4 on 2023-01-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('s_age', models.IntegerField()),
                ('s_phone', models.IntegerField()),
                ('s_add', models.TextField()),
            ],
        ),
    ]
